#! /bin/bash

#
# Usage:
#   build-builder-image <app> <dockerfile> [path]
#

ROOT=$(dirname $(realpath `dirname $0`))

APP=$1
DOCKER_FILE=$2
SOURCE_DIR=${3:-$ROOT}

if [ -n "$APP" -a -n "$DOCKER_FILE" -a -n "$SOURCE_DIR" ]; then
  NODE_BASE=node:18.20-slim
  RUBY_BUILDER_BASE=ruby:3.1.2-bullseye
  RUBY_RUNNER_BASE=ruby:3.1.2-slim-bullseye
  POSTGRESQL_VERSION=13 # Debian bullseye には 14 がない

  YARN_PATH=$(dirname $(dirname $(docker run --rm --entrypoint bash $NODE_BASE -c 'ls -l `which yarn`' | awk '{ print $NF }')))

  docker build \
         -t ${APP}-builder \
         --pull \
         --build-arg NODE_BASE=$NODE_BASE \
         --build-arg YARN_PATH=$YARN_PATH \
         --build-arg RUBY_BUILDER_BASE=$RUBY_BUILDER_BASE \
         --build-arg RUBY_RUNNER_BASE=$RUBY_RUNNER_BASE \
         --build-arg POSTGRESQL_VERSION=$POSTGRESQL_VERSION \
         -f $DOCKER_FILE \
         $SOURCE_DIR
else
  echo "build-builder-image"
  echo "Nothing to do"
fi
